Stage1
kkazlov/jet-start pull request #1
Opened 2021-10-08 12:07 UTC by kkazlov

to review

2021-10-08 14:26 UTC, kullias commented
если рефрешнуть страницу, получаем в деталях контакта undefined везде

2021-10-08 15:53 UTC, olimed reviewed
форма в попапе на странице Activity не очищается, когда введешь данные, а потом нажмешь кнопку cancel и снова открыть форму

2021-10-08 15:53 UTC, olimed commented on sources/views/activities.js
> +		};
можно сделать одну функцию и передавать третьим аргументом свойство:
`someFunction(a, b, "State")`

2021-10-08 15:53 UTC, olimed commented on sources/views/activities.js
> +		const contactSort = (a, b) => {
`activitySort `  and `contactSort` тоже можно сделать одну функцию и передать больше параметров

2021-10-08 15:53 UTC, olimed commented on sources/views/popup-constr.js
> +				filter: (item, value) => item.Value.toString().toLowerCase()
зачем здесь фильтр?

2021-10-08 15:53 UTC, olimed commented on sources/views/popup-constr.js
> +				filter: (item, value) => {
и тут?

2021-10-08 16:16 UTC, kullias requested changes

2021-10-08 16:16 UTC, kullias commented on sources/views/popup-constr.js
> +							this.$$("form").clearValidation();
вообще валидацию чистить стоит по хайду окна, вот это мастхэв
по смене фокуса в elementsConfig не подходит, поскольку касается и кнопок тоже (кнопка Add потеряла фокус при клике Cancel,а еще довольно странно, когда очистка подсветки делается по клику на Add до валидации, а потом валидация накидывает его опять)
если хочется чистить этот красный слой до закрытия успешно заполненной формы, то лучше уж какой onChange формы использовать (там можно еще и form.validate вызывать, если не хочешь чистить красную подсветку для всех полей и даже если ввод невалидный все равно)

2021-10-08 16:16 UTC, kullias commented on sources/views/activities.js
> +		const customSort = (a, b) => {
https://docs.webix.com/datatable__sorting.html#sortingbyaclickontheheader
мне кажется, у нас тут нет полей, которые требуют кастомной сортировки. "text", "date" и "int" справляются)

2021-10-08 16:16 UTC, kullias commented on sources/views/activities.js
> +			template: ({State}) => {
еще можно наш встроенный чекбокс использовать https://docs.webix.com/datatable__controls.html

2021-10-08 16:16 UTC, kullias commented on sources/views/popup-constr.js
> +				filter: (item, value) => item.Value.toString().toLowerCase()
не надо, оно по умолчанию фильтрует как надо

2021-10-08 16:16 UTC, kullias commented on sources/views/popup-constr.js
> +				filter: (item, value) => {
тоже не надо

2021-10-09 05:12 UTC, kkazlov commented on sources/views/popup-constr.js
> +				filter: (item, value) => item.Value.toString().toLowerCase()
Странно. У меня без фильтра была ошибка в консоли. Сейчас фильтр убрал - все работает хорошо.

2021-10-09 05:12 UTC, kkazlov commented on sources/views/popup-constr.js
> +				filter: (item, value) => {
убрал

2021-10-09 05:53 UTC, kkazlov commented on sources/views/activities.js
> +		};
done

2021-10-09 06:27 UTC, kkazlov commented on sources/myapp.js
> -			debug: !PRODUCTION,
!PRODUCTION = debug: true ?

2021-10-09 06:28 UTC, kkazlov commented on sources/styles/activities.css
> +.activiti-table [aria-rowindex]:nth-child(odd) {
done

2021-10-09 06:32 UTC, kkazlov commented on sources/views/activities.js
> +							text: "Do you want delete this record? Deleting cannot be undone."
done

2021-10-09 06:35 UTC, kkazlov commented on sources/views/activities.js
> +				this.refresh();
Убрал. Это был костыль, когда данные не успевали грузиться.

2021-10-09 06:37 UTC, kkazlov commented on sources/views/popup-constr.js
> +				filter: (item, value) => item.Value.toString().toLowerCase()
Убрал. В начале без фильтра были ошибки в консоли, поэтому и добавил. Сейчас все работает корректно и без фильтра.

2021-10-09 06:38 UTC, kkazlov commented on sources/views/popup-constr.js
> +				filter: (item, value) => {
убрал

2021-10-09 15:13 UTC, kkazlov commented on sources/views/top.js
> +			header.setValues({menuName: `${value}`});
done

2021-10-09 15:16 UTC, kkazlov commented on sources/views/contacts.js
> +			localId: "list",
done

2021-10-09 15:20 UTC, kkazlov commented on sources/views/contacts.js
> +		const infoTemplate = ({
done

2021-10-09 15:27 UTC, kkazlov commented on sources/views/contacts.js
> +			const status = statusesDB.getItem(statusID).Value;
done

2021-10-09 15:30 UTC, kkazlov commented on sources/views/contacts.js
> +			main.setValues({Status: status, StatusIcon: icon}, true);
done

2021-10-09 15:31 UTC, kkazlov commented on sources/views/activities.js
> +			template: ({State}) => {
done

2021-10-09 15:37 UTC, kkazlov commented on sources/views/activities.js
> +		btn.attachEvent("onItemClick", () => this._popup.showWindow());
done

2021-10-09 15:38 UTC, kkazlov commented on sources/views/activities.js
> +			click: () => this._popup.showWindow()
done

2021-10-09 15:40 UTC, kkazlov commented on sources/views/activities.js
> +				onDelete(e, id) {
done

2021-10-10 06:36 UTC, kkazlov commented on sources/views/activities.js
> +		this._popupEdit = this.ui(new PopupConstr(this.app, "Edit"));
done

2021-10-10 07:44 UTC, kkazlov commented on sources/views/popup-constr.js
> +							this.$$("form").clearValidation();
Исправил. Единственное - onChange из elementsConfig не сработал для textarea(Details). Пришлось добавить onFocus.
+ При закрытии popup, почему-то навешивался фокус на кнопку add activity(datatable). Не смог понять почему это происходит и использовал глобальную id, чтобы блюрить кнопку при закрытии popup. В popup lint ругается что $$() не определено. Это критичная ругань или можно так оставить?

2021-10-10 08:12 UTC, kkazlov commented on sources/views/activities.js
> +		const customSort = (a, b) => {
Исправил

2021-10-10 08:18 UTC, kkazlov commented on sources/views/activities.js
> +		};
Получилась стандартная сортировка, кастомную удалил.

2021-10-11 09:52 UTC, kullias commented on sources/views/activities.js
> +		});
чисто визуально у меня вот это работает хорошо, а ты что пробовал?

```js
this.on(activitiesDB.data, "onStoreUpdated", (id) => {
	if (id) table.filterByAll();
});
```

2021-10-11 09:55 UTC, kkazlov commented on sources/views/activities.js
> +		});
тоже самое, только без id и условия

2021-10-11 09:56 UTC, kullias commented on sources/views/popup-constr.js
> +							this.$$("form").clearValidation();
я писала про onChange формы. такой подход позволяет не создавать кучу обработчиков (на каждый инпут)

2021-10-11 10:04 UTC, kullias commented on sources/models/activitiesDB.js
> +			obj.check = obj.State === "Close" ? 1 : 0;
а может просто оставить Stage? и поменять on/off values (check/uncheck values)

2021-10-11 10:06 UTC, kullias commented on sources/models/activitiesDB.js
> +			activityTypesDB.waitData.then(() => {
модели не должны знать друг о друге
к тому же в этом нет необходимости, вебикс позволяет задавать collection для колонок
линковка таблиц может происходить на уровне вью (там где таблицы сводятся в одно представление)

2021-10-11 10:08 UTC, kkazlov commented on sources/views/popup-constr.js
> +							this.$$("form").clearValidation();
поставил onChange на форму, все равно не цепляет textarea. Я оставил способ с отдельным onFocus на textarea(только для этого поля).

2021-10-11 10:10 UTC, kullias commented on sources/views/activities.js
> +		});
проверка на айди нужна чтобы отсечь обновления конкретных айтемов от всего прочего (всякие перерисовки всего по разным поводам типа парсинга и рендеринга)

2021-10-11 10:33 UTC, kullias commented on sources/views/popup.js
> +		const details = this.$$("Details");
не надо, у textarea есть onChange и он передается в onChange формы
я даже локально проверила
так что:
- не надо этот onBlur
- не надо глобальная айди для кнопки
- не надо обращение к ней из другой вьюшки

2021-10-11 10:43 UTC, kullias commented on sources/views/activities.js
> +					prepare: (filterValue) => {
если в схеме модели преобразовать строки в даты, то все это не нужно (compare, prepare)

2021-10-11 11:16 UTC, kkazlov commented on sources/models/activitiesDB.js
> +			obj.check = obj.State === "Close" ? 1 : 0;
done

2021-10-11 11:36 UTC, kkazlov commented on sources/views/popup.js
> +		const details = this.$$("Details");
done

2021-10-11 12:39 UTC, kkazlov commented on sources/views/activities.js
> +					prepare: (filterValue) => {
done

2021-10-11 12:45 UTC, olimed commented on sources/views/activities.js
> +					value: "",
наверное, здесь стоит использовать свойство `Value`, несколько строк ниже именно это свойство ты используешь

2021-10-11 12:51 UTC, olimed commented on sources/views/activities.js
> +				return `${FirstName} ${LastName}`;
ты в Datacollection добавляешь свойство `value`, поэтому его можно использовать вместо FirstName и LastName

2021-10-11 13:14 UTC, kkazlov commented on sources/views/activities.js
> +					value: "",
да, точно, спс. Исправил

2021-10-11 13:36 UTC, olimed approved these changes

2021-10-11 15:36 UTC, kullias approved these changes

2021-10-11 15:37 UTC, merged