Stage2
kkazlov/jet-start pull request #2
Opened 2021-10-15 08:12 UTC by kkazlov

Stage2 to review

2021-10-15 12:51 UTC, kullias requested changes

2021-10-15 12:51 UTC, kullias commented on sources/views/contacts/contact-form.js
> +					contactsDB.updateItem(this._contactID, {Photo: ""});
вот это наверное странно
а если я захочу нажать Cancel в форме?

2021-10-15 12:51 UTC, kullias commented on sources/views/contacts/contact-form.js
> +						webix
это для глобальных айдишек, глобальные айди не нужны в джете и webix.$$ тоже

2021-10-15 12:51 UTC, kullias commented on sources/views/contacts/index.js
> +							localId: "contactLayout",
тут у одной ячейки локальная айди, у второй глобальная
странно
ты в принципе везде вызываешь для них лично просто show, тогда и обеим локальные норм
глобальная тут нужна для малтивью чтобы оно могло работать с ними и своим апи переключать https://docs.webix.com/api__ui.multiview_setvalue.html

2021-10-15 12:51 UTC, kullias commented on sources/views/contacts/index.js
> +		this.setParam("list", false, true);
вообще в фолс можно их и не сеттить. будут undefined, то же самое в этом случае
вообще решать показывать инфо или форму лучше без параметров, а через динамическое сабвью
show("info") или show("form") -- схематично

2021-10-15 12:51 UTC, kullias commented on sources/views/contacts/contact-form.js
> +			const formLabel = formState === "edit" ? "Edit" : "Add";
а вот это можно решить с помощью параметра id
если добавляем новый контакт, то стоит анселектнуть лист, айди сбросить

2021-10-15 12:51 UTC, kullias commented on sources/views/contacts/index.js
> +		const list = this.$$("list");
нехорошо лезть к виджетам внутри других вью
лист должен сам разбираться со своими данными и селектом и как раз управлять тем, какой контакт будем показывать

я бы представляла это примерно так:
- лист это класс и включен в индекс как статическое вью (следовательно параметры родителя для него будут как свои)
- в листе происходит селект, по событию выставляется параметр id
- детали и форма - это динамические сабвью, которые показываются в одном и том же месте ({ $subview:true })
- в урл чейндже деталей по этому айди берутся нужные данные
- форма, когда ее показывают, тоже берет по этому параметру нужные данные
- если мы добавляем новое событие, то лист надо анселектить, параметр сбрасывать (ну и лист блокировать тоже очень хорошая идея)
- если добавляем новый контакт, то следует это отследить и сделать на него селект

2021-10-15 12:51 UTC, kullias commented on sources/views/contacts/files-table.js
> +				onAfterFileAdd: function name() {
хэндлеры кликов и событий стоит вынести в метод класса чтобы не удлиннять конфиг

2021-10-15 12:51 UTC, kullias commented on sources/views/contacts/files-table.js
> +		const convertedSize = (size) => {
не стоит функции прямо внутри конфига определять. пусть это будет метод класса

2021-10-15 12:51 UTC, kullias commented on sources/views/contacts/files-table.js
> +				if (aConverted > bConverted) {
return aConverted - bConverted;

2021-10-15 12:51 UTC, kullias commented on sources/views/contacts/files-table.js
> +				else if (aConverted < bConverted) {
и else обычно не надо если ветки заканчиваются return

2021-10-15 12:51 UTC, kullias commented on sources/views/contacts/files-table.js
> +			sort: (a, b) => {
а может их лучше как инты сортировать, сохраняя при этом численный размер (там есть), а для показа в колонках использовать строковый? (в данных будет два поля, айди колонки будет от интового, а в темплейте показывать строковое поле)

2021-10-17 05:00 UTC, kkazlov commented on sources/views/contacts/info.js
> +					css: "info__label"
done

2021-10-17 05:00 UTC, kkazlov commented on sources/views/contacts/contact-form.js
> +				onChange: function change() {
done

2021-10-17 05:02 UTC, kkazlov commented on sources/models/filesDB.js
> +	data: [
done

2021-10-17 05:37 UTC, kkazlov commented on sources/views/contacts/contact-form.js
> +						webix
done

2021-10-17 11:43 UTC, olimed commented on sources/views/popup.js
>  		head.$view.innerText = this._popupType;
вместо `$view` можно использовать `getNode()`

2021-10-17 11:43 UTC, olimed commented on sources/views/contacts/activities-table.js
> +			rows: [datatable, {paddingY: 2, cols: [{}, AddActivityBtn]}]
очень похожую таблицу ты используешь на странице Activites,  можно создать отдельное вью для этой таблице и использовать его на разных страницах

2021-10-17 11:43 UTC, olimed commented on sources/views/contacts/contact-form.js
> +			this.$$("formLabel").setValue(`${formLabel} a new contact`);
немного не логичное сообщение получается, когда редактируешь существующий контакт
![image](https://user-images.githubusercontent.com/31127246/137625695-6645b662-b993-4167-8715-dc4ab96f5b5f.png)

2021-10-18 05:49 UTC, kkazlov commented on sources/views/contacts/index.js
> +							localId: "contactLayout",
done

2021-10-18 05:49 UTC, kkazlov commented on sources/views/contacts/index.js
> +		this.setParam("list", false, true);
done

2021-10-18 05:50 UTC, kkazlov commented on sources/views/contacts/contact-form.js
> +			const formLabel = formState === "edit" ? "Edit" : "Add";
done

2021-10-18 06:33 UTC, kkazlov commented on sources/views/contacts/files-table.js
> +				onAfterFileAdd: function name() {
done

2021-10-18 09:53 UTC, kkazlov commented on sources/views/activities.js
done

2021-10-18 09:54 UTC, kkazlov commented on sources/views/contacts/info.js
>  						<img src=${_photo} alt="photo">
done

2021-10-18 11:39 UTC, kkazlov commented on sources/views/popup.js
>  		head.$view.innerText = this._popupType;
done

2021-10-18 11:39 UTC, kkazlov commented on sources/views/contacts/activities-table.js
> +			rows: [datatable, {paddingY: 2, cols: [{}, AddActivityBtn]}]
done

2021-10-18 13:21 UTC, olimed commented on sources/views/contacts/contact-form.js
> +			Phone: value => value.length <= 20 && webix.rules.isNumber(value)
phone не должен быть числом, может присутствовать символ +, -, (,), space

2021-10-18 15:13 UTC, merged