Stage3
kkazlov/jet-start pull request #3
Opened 2021-10-20 11:24 UTC by kkazlov

Stage3 to review

2021-10-20 17:30 UTC, kullias requested changes

2021-10-20 17:30 UTC, kullias commented on sources/locales/en.js
> +};
![Selection_999(322)](https://user-images.githubusercontent.com/31205423/138138379-6e74536b-5d54-4aa9-bd9a-3f4af538cab4.png)

2021-10-20 17:30 UTC, kullias commented on sources/myapp.js
> +		app.use(plugins.Locale);
webix локаль тоже стоит задействовать, а то календарь не переводится, например

```
webix:{
		en:"en-US",
		// ...other locales
	}
```

2021-10-20 17:30 UTC, kullias commented on sources/views/activities.js
> +		const tomorrow = +new Date().setHours(0, 0, 0, 0) + 1000 * 60 * 60 * 24;
норм, а еще у нас в webix есть Date.add (можно к сегодняшней дате добавить день и потом убрать время dayStart)

2021-10-20 17:30 UTC, kullias commented on sources/views/activities.js
> +		const tomorrow = +new Date().setHours(0, 0, 0, 0) + 1000 * 60 * 60 * 24;
можно не преобразовывать после setHours в число потому что typeof new Date().setHours(0, 0, 0, 0) === "number"

2021-10-20 17:30 UTC, kullias commented on sources/views/activities.js
> +		return date >= startWeek && date <= endWeek;
тоже норм, но вебикс и тут может помочь, потому что тоже есть готовые методы
weekStart, add, dayStart

2021-10-20 17:30 UTC, kullias commented on sources/views/activities.js
> +		return thisYear === objYear && thisMonth === objMonth;
monthStart тоже есть

2021-10-20 17:30 UTC, kullias commented on sources/views/activities.js
> +		switch (btnValue) {
вот это все уже было и мб можно все в один метод вынести?

2021-10-20 17:30 UTC, kullias commented on sources/views/settings/index.js
> +		const value = this.getRoot().queryView({name: "lang"}).getValue();
я в доке уже успела поправить эту немного досадную штуку с queryView
лучше пользоваться localId и this.$$

2021-10-20 17:30 UTC, kullias commented on sources/views/settings/settings-constr.js
> +		this._dataBase = dataBase;
можно без сохранения в константу обойтись, я думаю) прямо config.dataBase и все дела

2021-10-21 05:37 UTC, kkazlov commented on sources/myapp.js
> +		app.use(plugins.Locale);
о круто. А я думал, как в confirm кнопки перевести. Оказывается, при помощи локалей) Спасибо!

2021-10-21 06:25 UTC, kkazlov commented on sources/views/settings/settings-constr.js
> +		this._dataBase = dataBase;
Исправил. У меня были еще переменные, потом я их убрал и этот момент забыл убрать)

2021-10-21 10:37 UTC, olimed commented on sources/views/activities.js
> +		switch (id || btnValue) {
в каждом case ты делаешь одну и туже проверку, наверное. лучше вынести это до switch

2021-10-21 11:42 UTC, kkazlov commented on sources/views/activities.js
> +				break;
done

2021-10-21 11:43 UTC, olimed approved these changes

2021-10-21 11:54 UTC, kullias approved these changes

2021-10-21 12:08 UTC, merged